### ISSUE TITLE
Options crash the game

### ISSUE THREAD

**Issue by RyutoSetsujin** [Assimileafy/itgAC-oitg-port#1]
Parse error in ScreenOptionsMaster::OpenITG Options

Version: NITG 4.3.0

[log.txt](https://github.com/smworkshop/ITG1AC-OITG-port/files/13643677/log.txt)

**Comment by Assimileafy** [comment]
Cannot reproduce error. Seems to be due to missing scripts related to OpenITG? We can try including those scripts to see if that fixes it.

**Comment by Assimileafy** [comment]
issue seems to be due to missing patch.zip file in NotITG program. Notified Devs. Not an issue of this project, but will list down as a REQUIREMENT.
